---
- name: Ubuntu STIG Roles
  hosts: 192.168.1.25
  become: true
  gather_facts: true
  roles:
    #- roles/UBUNTU20-STIG
    - roles/ubuntu2004STIG
    - roles/ubuntu2204STIG
    - roles/UBUNTU22-STIG
  vars:
    inactivity_days: 35
    pam_faillock_dir: "/etc/security/faillock"
    fips_enabled: true

  tasks:

    # -------------------------------------------------------------------
    # APT hardening
    # -------------------------------------------------------------------
    - name: Ensure APT requires signed packages (V-260476)
      copy:
        dest: /etc/apt/apt.conf.d/99verify
        content: |
          APT::Get::AllowUnauthenticated "false";
          Acquire::AllowInsecureRepositories "false";
          Acquire::AllowDowngradeToInsecureRepositories "false";

    - name: Ensure APT removes obsolete packages after updates (V-260477)
      copy:
        dest: /etc/apt/apt.conf.d/99autoremove
        content: |
          APT::Get::AutomaticRemove "true";
          APT::Get::Purge "true";

    # -------------------------------------------------------------------
    # Packages
    # -------------------------------------------------------------------
    - name: Remove systemd-timesyncd (V-260480)
      apt:
        name: systemd-timesyncd
        state: absent

#    - name: Ensure ufw installed (V-260514)
#      apt:
#        name: ufw
#        state: present

    # -------------------------------------------------------------------
    # Firewall
    # -------------------------------------------------------------------
#    - name: Enable and start ufw (V-260515, V-260516)
#      ufw:
#        state: enabled
#        policy: deny

    # -------------------------------------------------------------------
    # PAM hardening
    # -------------------------------------------------------------------
    - name: Configure PAM to prohibit cached authentications older than 1 day (V-260581)
      lineinfile:
        path: /etc/security/faillock.conf
        regexp: '^#?dir ='
        line: 'dir = /var/run/faillock'
        state: present

    - name: Set pam_faillock unlock time to 86400 seconds (1 day)
      lineinfile:
        path: /etc/security/faillock.conf
        regexp: '^#?unlock_time ='
        line: 'unlock_time = 86400'
        state: present
    - name: Disable blank passwords (V-260570)
      lineinfile:
        path: /etc/pam.d/common-auth
        regexp: '^auth\s+required\s+pam_unix.so'
        line: 'auth required pam_unix.so nullok_secure'

    # -------------------------------------------------------------------
    # Kernel & core dumps
    # -------------------------------------------------------------------
    - name: Disable core dumps (V-260473)
      copy:
        dest: /etc/security/limits.d/99-coredumps.conf
        content: |
          * hard core 0

    - name: Disable apport (Ubuntu crash dump service)
      systemd:
        name: apport
        state: stopped
        enabled: no
      ignore_errors: yes

    - name: Disable core dumps in limits.conf (V-260473)
      copy:
        dest: /etc/security/limits.d/99-coredumps.conf
        content: |
          * hard core 0

    - name: Ensure core_pattern prevents dumps to filesystem
      sysctl:
        name: kernel.core_pattern
        value: "|/bin/false"
        state: present
        sysctl_set: yes
        reload: yes

    # -------------------------------------------------------------------
    # SSH Configuration
    # -------------------------------------------------------------------
    - name: Harden SSH with FIPS 140-3 approved ciphers (V-260531)
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^Ciphers'
        line: 'Ciphers aes256-ctr,aes192-ctr,aes128-ctr'
        create: yes
      notify: Restart ssh

    # -------------------------------------------------------------------
    # Journald
    # -------------------------------------------------------------------
    - name: Restrict journalctl to adm group (V-260512)
      file:
        path: /usr/bin/journalctl
        mode: '0750'
        group: adm

    - name: Restrict journal verbosity (V-260489, V-260490)
      lineinfile:
        path: /etc/systemd/journald.conf
        regexp: '^#?ForwardToConsole='
        line: 'ForwardToConsole=no'

    # -------------------------------------------------------------------
    # Password hashing
    # -------------------------------------------------------------------
    - name: Enforce SHA-512 password hashing (V-260569, V-260572)
      lineinfile:
        path: /etc/login.defs
        regexp: '^ENCRYPT_METHOD'
        line: 'ENCRYPT_METHOD SHA512'

    # -------------------------------------------------------------------
    # Inactive account lockout
    # -------------------------------------------------------------------
    - name: Lock accounts inactive for 35 days (V-260547)
      lineinfile:
        path: /etc/default/useradd
        regexp: '^INACTIVE='
        line: "INACTIVE={{ inactivity_days }}"

    # -------------------------------------------------------------------
    # Boot authentication
    # -------------------------------------------------------------------
    - name: Require password for single-user mode (V-260470)
      lineinfile:
        path: /usr/lib/systemd/system/rescue.service
        regexp: '^ExecStart='
        line: 'ExecStart=-/bin/sh -c "/sbin/sulogin; exec /bin/systemd-sysv-generator rescue.target"'

    # -------------------------------------------------------------------
    # Library permissions
    # -------------------------------------------------------------------
    - name: Ensure /lib and /usr/lib files are group-owned by root (V-260500)
      file:
        path: "{{ item }}"
        recurse: yes
        group: root
        state: directory
      with_items:
        - /usr/lib

    - name: Ensure library files are group-owned by root (V-260500)
      file:
        path: "{{ item }}"
        recurse: yes
        group: root
        state: directory
      loop:
        - /usr/lib
        - /usr/local/lib
