---

- name: LOW | UBTU-24-400340 | PATCH | Ubuntu 24.04 LTS must be configured such that Pluggable Authentication Module (PAM) prohibits the use of cached authentications after one day.
  when:
    - ubtu24stig_400340
    - ubtu24stig_use_sssd
    - "'sssd' in ansible_facts.packages"
  tags:
    - UBTU-24-400340
    - CAT3
    - CCI-002007
    - SRG-OS-000383-GPOS-00166
    - SV-270734r1066691_rule
    - V-270734
    - NIST800-53R4_IA-5
    - authorise
  block:
    - name: LOW | UBTU-24-400340 | AUDIT | Ubuntu 24.04 LTS must be configured such that Pluggable Authentication Module (PAM) prohibits the use of cached authentications after one day. | find current settings
      ansible.builtin.find:
        paths: /etc/sssd
        contains: ^\s*offline_credentials_expiration\s*=\s*((?!1).)*$
        recurse: true
        pattern: '*.conf'
        read_whole_file: true
      register: discovered_security_cached_auth_timeout

    - name: LOW | UBTU-24-400340 | PATCH | Ubuntu 24.04 LTS must be configured such that Pluggable Authentication Module (PAM) prohibits the use of cached authentications after one day. | comment out settings
      when: "'/etc/security/limits.conf' not in item"
      ansible.builtin.lineinfile:
        path: "{{ item }}"
        backrefs: true
        regexp: ^\s*offline_credentials_expiration(.*)
        line: '#offline_credentials_expiration \1'
      loop: "{{ discovered_security_cached_auth_timeout.files }}"

    - name: LOW | UBTU-24-400340 | PATCH | Ubuntu 24.04 LTS must be configured such that Pluggable Authentication Module (PAM) prohibits the use of cached authentications after one day. | Ensure settings exist
      ansible.builtin.lineinfile:
        path: /etc/sssd/sssd.conf
        regexp: ^(#|)\s*offline_credentials_expiration\s*=\s*(?!1)
        line: offline_credentials_expiration = 1
