---
# vars file for UBUNTU24-STIG

min_ansible_version: 2.12.1

# Set dynamically if discovered to be non UEFI boot
ubtu24stig_legacy_boot: false

# tweak role to run in a non-privileged container (default value)- dynamically discovered in tasks/main.yml
system_is_container: false

# Default set for discovery
ubtu24stig_subscribed: false

# Used to control warning summary
warn_control_list: ""
warn_count: 0

# Allow automated discovery of uids
discover_int_uid: true

# Default for facts
reboot_required: false
update_audit_template: false

# DOD encryption
ubtu24stig_dod_ciphers:
  - aes256-gcm@openssh.com
  - aes128-gcm@openssh.com
  - aes256-ctr
  - aes128-ctr
ubtu24stig_dod_macs:
  - hmac-sha2-512-etm@openssh.com
  - hmac-sha2-256-etm@openssh.com
  - hmac-sha2-512
  - hmac-sha2-256
ubtu24stig_dod_kex:
  - ecdh-sha2-nistp521
  - ecdh-sha2-nistp384
  - ecdh-sha2-nistp256
  - diffie-hellman-group-exchange-sha256
  - diffie-hellman-group16-sha512
  - diffie-hellman-group14-sha256
