---

- name: MEDIUM | UBTU-24-909000 | Ubuntu 24.04 LTS audit system must protect auditing rules from unauthorized change.
  when: ubtu24stig_909000
  tags:
    - UBTU-24-909000
    - CAT2
    - CCI-000163
    - SRG-OS-000058-GPOS-00028
    - SV-270832r1068399_rule
    - V-270832
    - NIST800-53R4_AU-9
    - auditd
  ansible.builtin.set_fact:
    update_audit_template: true
